- name: restart httpd
  hosts: servidores
  become: true
  tasks:
    - name: httpd stop
      ansible.builtin.service:
        name: httpd
        state: stopped
        enabled: true
    - name: httpd start
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
